version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=usersdb
      - TZ=Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # <-- persist Postgres

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ordersdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql               # <-- persist MySQL


  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]  # enables AOF persistence
    volumes:
      - redis_data:/data   # persist Redis data (optional if you want persistence)
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:
  redis_data:
