spring:
  application:
    name: B-user-service
  config:
    import: "configserver:http://localhost:8888"   # <- required in latest Spring Cloud
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/